### PR TITLE
Add support for newline-delimited JSON

### LINKED ISSUE #12: Support newline-delimited GeoJSON
Example here: https://gist.github.com/eyeseast/faee3683d305d4b6f80a2f20fce79a4a

This format feels worth supporting because it can be streamed - so the tool could consume potentially GBs of GeoJSON data without having to load it all into RAM first.

### PR DESCRIPTION
**Pull request by eyeseast**
☝️ does that. Closes #12 

A couple caveats:

- Features are streamed in with a generator, since this is intended for large datasets. That means we can't look ahead at the first 100 features.
- We can't auto-detect feature IDs using ndjson. I'm ok with that. You can still pass `--pk=id` and get the same thing.
- We can't use the first 100 features to build the initial table. Again, I think it's fine. I note in the README how to grab a subset using Fiona.

I have one test here, but I'm very much open to suggestions for more.

### CODE REVIEW

**Comment by simonw** [comment]
There's a pattern for peeking ahead in sqlite-utils here:

https://github.com/simonw/sqlite-utils/blob/e8b2b7383bd94659d3b7a857a1414328bc48bc19/sqlite_utils/db.py#L993-L1004

You can use `itertools.islice` to pull out the first 100 items (and turn them into a list with `list()`), then use `itertools.chain(that_list, original_iterator)` to loop through the first 100 items followed by the rest of the iterator.

**Comment by simonw** [comment]
This looks great - the tests look robust enough to me.

**Comment by eyeseast** [comment]
Cool. I'll see if I can get the peek-ahead to work in a reasonable way. Was thinking about `islice` but wasn't totally sure where to do that with `yield_records` also happening.

**Comment by eyeseast** [comment]
I got `feature.id` working by sampling the stream of features coming in, and then chaining that sample back into the original stream.

Getting it to work with processed features to guess column types starts to feel precarious, because lists and generators are going to operate differently. It might ultimately be easier to do `features = iter(features)` at the top, so it's always a one-way stream and everything operates the same, but I'm not sure that's worth it. I think collecting a subset into a feature collection, like I describe in the readme, actually feels a little easier and more deliberate.

**Pull request merged**
